spring.application.name=auth-api

#Start with the Data Source
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver

#H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA/ Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#JWT (custom -you name these, we'll read them later with @Value)
app.jwt.secret=mySecretKey1234567890abcdefghij
app.jwt.expiration=86400000

#Seed data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
